aspatal/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls',namespace="users")),
    path('',include('aspatal_app.urls',namespace="aspatal_app")),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name="users"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path("profile/", views.UpdatedUserProfile, name="profile"),
    path("profile/create/", views.CreateUserProfile, name="profile-create"),
    path("profile/<int:pk>/", views.UpdatedUserProfilePk, name="profile-pk"),
    path("profile/doc/<int:pk>/", views.UpdatedDocProfilePk, name="doc-profile-pk"),
    path("profile/<int:pk>/delete/", views.DeleteUserProfilePk, name="profile-delete"),
    path("profile/doc/<int:pk>/delete/", views.DeleteDocProfilePk, name="doc-profile-delete"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.contrib.auth import get_user_model

REGISTER_AS = [
    ('D', 'Doctor'),
    ('P', 'Patient'),
    ('R', 'Receptionist'),
    ('HR','HR')
]

GENDER_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other')
]

BLOOD_GROUPS = [
    ('O-', 'O-'),
    ('O+', 'O+'),
    ('A-', 'A-'),
    ('A+', 'A+'),
    ('B-', 'B-'),
    ('B+', 'B+'),
    ('AB-', 'AB-'),
    ('AB+', 'AB+'),
]

class User(AbstractUser):
    registeras = models.CharField(choices=REGISTER_AS, max_length=2)

    def is_doctor(self):
        if self.registeras == 'D':
            return True
        else:
            return False

    def is_patient(self):
        if self.registeras == 'P':
            return True
        else:
            return False

    def is_receptionist(self):
        if self.registeras == 'R':
            return True
        else:
            return False

    def is_HR(self):
        if self.registeras == 'HR':
            return True
        else:
            return False

    class Meta:
        ordering = ('id',)


class UserProfile(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='user_profile')
    name = models.CharField(max_length=50)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$')
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    email = models.EmailField(blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=1, blank=True)
    age = models.IntegerField(blank=True, null=True)
    address = models.CharField(max_length=500, blank=True)
    blood_group = models.CharField(choices=BLOOD_GROUPS, max_length=3, blank=True)
    case_paper = models.IntegerField(blank=True, null=True)
    department = models.CharField(max_length=50, null=True, blank=True)
    salary = models.IntegerField(null=True, blank=True)
    attendance = models.IntegerField(null=True, blank=True)
    status = models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], null=True, blank=True,
                              max_length=8)

    def __str__(self):
        return "{}-Profile".format(self.user)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import *

REGISTER_AS = [
    ('D', 'Doctor'),
    ('P', 'Patient')
]

GENDER_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other')
]

class UserCreateForm(UserCreationForm):
    register_as = forms.ChoiceField(choices=REGISTER_AS, required=True, widget=forms.RadioSelect)
    class Meta:
        fields = ("first_name", "last_name", "username", "email", "password1", "password2", "register_as")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Username"
        self.fields["email"].label = "Email address"

class ProfileUpdateForm(forms.ModelForm):
    gender = forms.ChoiceField(choices=GENDER_CHOICES, required=False, widget=forms.RadioSelect)
    class Meta:
        model = UserProfile
        fields = ('name', 'phone', 'email', 'gender', 'age', 'address', 'blood_group','case_paper')


class DoctorProfileForm(forms.ModelForm):
    gender = forms.ChoiceField(choices=GENDER_CHOICES, required=False, widget=forms.RadioSelect)
    class Meta:
        model = UserProfile
        fields = ('name', 'phone', 'email', 'gender', 'age', 'address', 'department', 'attendance', 'salary', 'status')

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import *
import string
import random
from django.contrib import messages

def register(request):
    if request.method=='POST':
        form=UserCreateForm(request.POST)
        if form.is_valid():
            user=form.save()
            f_name=user.first_name
            l_name=user.last_name
            name=f_name+' '+l_name
            UserProfile.objects.create(name=name,user=user)
            messages.success(request,f'Account created for {f_name}')
            return redirect('aspatal_app:home')
    else:
        form = UserCreateForm()
    return render(request,'users/register.html',{'form':form})

def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

@login_required(login_url='/login/')
def CreateUserProfile(request):
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            password = User.objects.make_random_password()
            username = profile.name.split()[0] + id_generator()
            user = User.objects.create(username=username, registeras="P")
            user.set_password(password)
            user.save_base(raw=True)
            profile.user = user
            profile.save()
            return redirect('aspatal_app:r_dashboard')
    form = ProfileUpdateForm()
    return render(request, 'users/profile_create.html', {'form': form})


@login_required(login_url='/login/')
def UpdatedUserProfile(request):
    user = request.user
    profile = UserProfile.objects.get(user=user)
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = ProfileUpdateForm(instance=profile)
    return render(request, 'users/profile.html', {'form': form, 'user':user})


@login_required(login_url='/login/')
def UpdatedUserProfilePk(request, pk):
    user = User.objects.get(pk=pk)
    profile = UserProfile.objects.get(user=user)
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('aspatal_app:r_dashboard')
    else:
        form = ProfileUpdateForm(instance=profile)
    return render(request, 'users/profile.html', {'form': form, 'user':user})


@login_required(login_url='/login/')
def UpdatedDocProfilePk(request, pk):
    user = User.objects.get(pk=pk)
    profile = UserProfile.objects.get(user=user)
    if request.method == 'POST':
        form = DoctorProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('aspatal_app:hr_dashboard')
    else:
        form = DoctorProfileForm(instance=profile)
    return render(request, 'users/profile.html', {'form': form, 'user':user})


@login_required(login_url='/login/')
def DeleteUserProfilePk(request, pk):
    user = User.objects.get(pk=pk)
    profile = UserProfile.objects.get(user=user)
    if request.method == 'POST':
        user.delete()
        return redirect('aspatal_app:r_dashboard')
    else:
        return render(request, 'users/profile_delete.html', {'user':user})


@login_required(login_url='/login/')
def DeleteDocProfilePk(request, pk):
    user = User.objects.get(pk=pk)
    profile = UserProfile.objects.get(user=user)
    if request.method == 'POST':
        user.delete()
        return redirect('aspatal_app:hr_dashboard')
    else:
        return render(request, 'user_profile/profile_doc_delete.html', {'user':user})

users/templates/users/login.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|Login
{% endblock %}
{% block content %}
    <div class="content-section">
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account?<a href="{% url 'users:register' %}" class="ml-2">Sign up</a>
            </small>
        </div>
    </div>
{% endblock %}

users/templates/users/logout.html
{% extends 'aspatal_app/index.html' %}

{% block title %}
    Life|ReLogin
{% endblock %}
{% block content %}
        <h2>You have been logout..</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'users:login' %}" class="ml-2">Log In Again</a>
            </small>
        </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h2>Hello, {{ user.username }}</h2>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Update" class="btn btn-primary">
    </form>
</div>
{% endblock %}

users/templates/users/profile_create.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|Create_prof
{% endblock %}
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Create" class="btn btn-default">
    </form>
</div>
{% endblock %}

users/templates/users/profile_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/users/register.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|Register
{% endblock %}
{% block content %}
    <div class="content-section">
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have an account?<a href="{% url 'users:register' %}" class="ml-2">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}