aspatal/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls',namespace="users")),
    path('',include('aspatal_app.urls',namespace="aspatal_app")),
]

aspatal_app/urls.py
from django.urls import path
from . import views

app_name="aspatal_app"

urlpatterns = [
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('contact',views.contact,name='contact'),
    path("appointments/p/", views.AppointmentsForAPatientView.as_view(), name="patient-appointments"),
    path("appointments/d/", views.AppointmentsForADoctorView.as_view(), name="doctor-appointments"),
    path("medHistory/", views.MedicalHistoryView.as_view(), name="med-history"),
    path("prescriptions/", views.PrescriptionListView.as_view(), name="doc-prescriptions"),
    path("prescription/create", views.PrescriptionCreateView, name="doc-prescriptions-create"),
    path("appointment/create", views.AppointmentCreateView, name="appointment-create"),
    path("rdashboard/", views.rdashboard, name="r_dashboard"),
    path("hrdashboard/", views.hrdashboard, name="hr_dashboard"),
    path("hraccounting/", views.hraccounting, name="hr_accounting"),
    path("payments/", views.pateintpayments, name="pat_payments"),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name="users"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path("profile/", views.UpdatedUserProfile, name="profile"),
    path("profile/create/", views.CreateUserProfile, name="profile-create"),
    path("profile/<int:pk>/", views.UpdatedUserProfilePk, name="profile-pk"),
    path("profile/doc/<int:pk>/", views.UpdatedDocProfilePk, name="doc-profile-pk"),
    path("profile/<int:pk>/delete/", views.DeleteUserProfilePk, name="profile-delete"),
    path("profile/doc/<int:pk>/delete/", views.DeleteDocProfilePk, name="doc-profile-delete"),
]

aspatal_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

class Appointment(models.Model):
    date = models.DateField()
    time = models.TimeField()
    status = models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10)
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patient')
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='doctor')

    def __str__(self):
        return "Patient - {} Doc- {} At {} {}".format(self.patient, self.doctor, self.date, self.time)


class Prescription(models.Model):
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='doctor_prescription')
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patient_prescription')
    date = models.DateField(auto_now_add=True)
    symptoms = models.CharField(max_length=200)
    prescription = models.TextField()

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return "Presciption Doc-{} Patient-{}".format(self.doctor, self.patient)

PAYMENT_TYPES = [
    ('I','Individual'),
    ('C','Consulting')
]

class Payment(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name="patient_payments")
    date = models.DateField(auto_now_add=True)
    paid = models.IntegerField(null=True)
    outstanding = models.IntegerField(null=True)
    total = models.IntegerField(null=True)
    payment_type = models.CharField(choices=PAYMENT_TYPES, max_length=1, default="I")

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return "Payment Patient-{} Amount-{}".format(self.patient, self.total)

aspatal_app/forms.py
from django import forms
from .models import *
from django.contrib.auth import get_user_model
User = get_user_model()

class PrescriptionForm(forms.ModelForm):

    class Meta:
        model = Prescription
        fields = ('patient', 'symptoms', 'prescription')

    def __init__(self, *args, **kwargs):
        super(PrescriptionForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['patient'].queryset = User.objects.filter(registeras="P")


class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['patient'].queryset = User.objects.filter(registeras="P")
            self.fields['doctor'].queryset = User.objects.filter(registeras="D")
            self.fields["date"].label = "Date (YYYY-MM-DD)"
            self.fields["time"].label = "Time 24 hr (HH:MM)"

aspatal_app/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import UserProfile

def home(request):
    return render(request,'aspatal_app/home.html')

def about(request):
    return render(request,'aspatal_app/about.html')

def contact(request):
    return render(request, 'aspatal_app/contact.html')

class AppointmentsForAPatientView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'users:login'

    def get_queryset(self):
        return Appointment.objects.filter(patient=self.request.user)


class AppointmentsForADoctorView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'account:login'

    def get_queryset(self):
        return Appointment.objects.filter(doctor=self.request.user)


class MedicalHistoryView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'account:login'

    def get_queryset(self):
        return Prescription.objects.filter(patient=self.request.user)


class PrescriptionListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'users:login'

    def get_queryset(self):
        return Prescription.objects.filter(doctor=self.request.user)


@login_required(login_url='/login/')
def PrescriptionCreateView(request):
    if request.method == 'POST':
        form = PrescriptionForm(request.POST)
        if form.is_valid():
            prescription = form.save(commit=False)
            prescription.doctor = request.user
            prescription.save()
            return redirect('aspatal_app:doc-prescriptions')
    else:
        form = PrescriptionForm()
    return render(request, 'aspatal_app/prescription_create.html', {'form': form})


@login_required(login_url='/login/')
def AppointmentCreateView(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.save()
            return redirect('aspatal_app:r_dashboard')
    else:
        form = AppointmentForm()
    return render(request, 'aspatal_app/appointment_create.html', {'form': form})


@login_required(login_url='/login/')
def rdashboard(request):
    if request.method == "GET" and request.user.registeras == "R":
        context = {
            "totalApp" : len(Appointment.objects.all()),
            "compApp" : len(Appointment.objects.filter(status="Completed")),
            "pendApp" : len(Appointment.objects.filter(status="Pending")),
            "app_list" : Appointment.objects.all(),
            "pat_list" : UserProfile.objects.filter(user__registeras="P")[:5]
        }
        return render(request, 'aspatal_app/recp_dashboard.html', context=context)


@login_required(login_url='/login/')
def hrdashboard(request):
    if request.method == "GET" and request.user.registeras == "HR":
        context = {
            "totalPat" : len(User.objects.filter(registeras="P")),
            "totalDoc" : len(User.objects.filter(registeras="D")),
            "ondutyDoc" : len(UserProfile.objects.filter(status="Active").filter(user__registeras="D")),
            "doc_list" : UserProfile.objects.filter(user__registeras="D")
        }
        return render(request, 'aspatal_app/hr_dashboard.html', context=context)


@login_required(login_url='/login/')
def hraccounting(request):
    if request.method == "GET" and request.user.registeras == "HR":
        context = {
            "payment_ind" : Payment.objects.filter(payment_type="I"),
            "payment_cons" : Payment.objects.filter(payment_type="C"),
        }
        return render(request, 'aspatal_app/accounting.html', context=context)


@login_required(login_url='/login/')
def pateintpayments(request):
    if request.method == "GET":
        context = {
            "payment_me" : Payment.objects.filter(patient=request.user),
        }
        return render(request, 'aspatal_app/payment_invoice.html', context=context)

aspatal_app/templates/aspatal_app/about.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|Aboutus
{% endblock %}
{% block content %}

    <h1 align="center">About Us</h1>

{% endblock %}

aspatal_app/templates/aspatal_app/accounting.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|account
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-5">
        <h3>Individuals' Outstandings</h3>
        <div class="card card-body">
            <table class="table table-striped">
                <thead>
                    <th>Patient</th>
                    <th>Outstanding</th>
                    <th>Paid</th>
                    <th>Reminder</th>
                </thead>
                {% for obj in payment_ind %}
                <tr>
                    <td>{{ obj.patient }}</td>
                    <td>{{ obj.outstanding }}</td>
                    <td>{{ obj.paid }}</td>
                    <td><button class="btn btn-primary">Set Reminder</button></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-md-7">
        <h3>Consultings' Outstandings</h3>
        <div class="card card-body">
            <table class="table table-striped">
                <thead>
                    <th>Date</th>
                    <th>Patient Name</th>
                    <th>Paid</th>
                    <th>Outstanding</th>
                    <th>Total</th>
                    <th>Invoice</th>
                </thead>
                {% for obj in payment_cons %}
                <tr>
                    <td>{{ obj.date }}</td>
                    <td>{{ obj.patient }}</td>
                    <td>{{ obj.paid }}</td>
                    <td>{{ obj.outstanding }}</td>
                    <td>{{ obj.total }}</td>
                    <td><a href="{% url 'aspatal_app:pat_payments' %}">Open Invoice</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

aspatal_app/templates/aspatal_app/appointment_create.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|create_appointment
{% endblock %}
{% block content %}
<div class="container">
    <h2>Create an Appointment</h2>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Create" class="btn btn-default">
    </form>
</div>
{% endblock %}

aspatal_app/templates/aspatal_app/appointment_list.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|Appointment_List
{% endblock %}
{% block content %}
<div class="container">
    <h2>Your Appointments</h2>
    <div>
        {% if user.is_patient %}
        <table class="table table-striped">
            <thead>
                <th>Date</th>
                <th>Time</th>
                <th>Consulting Doctor</th>
                <th>Status</th>
            </thead>
            {% for obj in object_list %}
            <tr>
                <td>{{ obj.date }}</td>
                <td>{{ obj.time }}</td>
                <td>{{ obj.doctor }}</td>
                <td>{{ obj.status }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        {% if user.is_doctor %}
        <table class="table table-striped">
            <thead>
                <th>Date</th>
                <th>Time</th>
                <th>Patient Info</th>
            </thead>
            {% for obj in object_list %}
            <tr>
                <td>{{ obj.date }}</td>
                <td>{{ obj.time }}</td>
                <td>{{ obj.patient }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

aspatal_app/templates/aspatal_app/contact.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|Contact
{% endblock %}
{% block content %}
    <h1 align="center">Contact Us</h1>

{% endblock %}

aspatal_app/templates/aspatal_app/hr_dashboard.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|HR_Dashboard
{% endblock %}
{% block content %}
<div class="container">
    <h1 align="center">Dashboard</h1>
    <br>
    <ul class="list-group">
        <li class="list-group-item">
            <strong>Total Doctors</strong> - {{ totalDoc }}
        </li>
        <li class="list-group-item">
            <strong>Total Patients</strong> - {{ totalPat }}
        </li>
        <li class="list-group-item">
            <strong>On Duty Doctors</strong> - {{ ondutyDoc }}
        </li>
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <h3>Doctors</h3>
        <div class="card card-body">
            <table class="table table-striped">
                <thead>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>Age</th>
                    <th>Status</th>
                    <th>Department</th>
                    <th>Attendance</th>
                    <th>Salary</th>
                    <th>Update</th>
                    <th>Remove</th>
                </thead>
                {% for obj in doc_list %}
                <tr>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.phone }}</td>
                    <td>{{ obj.email }}</td>
                    <td>{{ obj.gender }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.status }}</td>
                    <td>{{ obj.department }}</td>
                    <td>{{ obj.attendance }}</td>
                    <td>{{ obj.salary }}</td>
                    <td><a href="{% url 'users:doc-profile-pk' pk=obj.user.id %}"><button class="btn btn-warning">Update</button></a></td>
                    <td><a href="{% url 'users:doc-profile-delete' pk=obj.user.id %}"><button class="btn btn-danger">Delete</button></a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

aspatal_app/templates/aspatal_app/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet"  type="text/css"  href="{% static 'aspatal_app/style.css' %}">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <title>
    {% block title %} {% endblock %}
  </title>
</head>
<body>
{% if user.is_authenticated and user.is_patient %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">LIFE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:about' %}">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:contact' %}">Contacts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:patient-appointments' %}">Your appointment's</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:pat_payments' %}">Invoice and Payment</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:med-history' %}">Medical history</a>
      </li>
    </ul>
    <a href="{% url 'users:profile' %}"style="color:white;font-size:20pt;" class="mr-4">Welcome {{user.username}}</a>
    <a href="{% url 'users:logout' %}" style="color:white;font-size:20pt;">Logout</a>
  </div>
</nav>

{% elif user.is_authenticated and user.is_doctor %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">LIFE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:about' %}">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:contact' %}">Contacts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:doctor-appointments' %}">Appointment</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:doc-prescriptions' %}">Presciption</a>
      </li>

    </ul>
    <a href="{% url 'users:doc-profile-pk' pk=user.pk %}"style="color:white;font-size:20pt;" class="mr-4">Welcome Dr. {{user.username}}</a>
    <a href="{% url 'users:logout' %}" style="color:white;font-size:20pt;">Logout</a>
  </div>
</nav>

{% elif user.is_authenticated and user.is_receptionist %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">LIFE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:about' %}">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:contact' %}">Contacts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:r_dashboard' %}">Dashboard</a>
      </li>

    </ul>
    <a href="{% url 'users:doc-profile-pk' pk=user.pk %}"style="color:white;font-size:20pt;" class="mr-4">Welcome {{user.username}}</a>
    <a href="{% url 'users:logout' %}" style="color:white;font-size:20pt;">Logout</a>
  </div>
</nav>

{% elif user.is_authenticated and user.is_HR %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">LIFE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:about' %}">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:contact' %}">Contacts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:hr_dashboard' %}">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:hr_accounting' %}">Accounting</a>
      </li>

    </ul>
    <a href="{% url 'users:doc-profile-pk' pk=user.pk %}"style="color:white;font-size:20pt;" class="mr-4">Welcome {{user.username}}</a>
    <a href="{% url 'users:logout' %}" style="color:white;font-size:20pt;">Logout</a>
  </div>
</nav>

{% else%}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">LIFE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:about' %}">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'aspatal_app:contact' %}">Contacts</a>
      </li>

    </ul>
    <a href="{% url 'users:login' %}" style="color:white;font-size:10pt;" class="mr-4">Login</a>
    <a href="{% url 'users:register' %}" style="color:white;font-size:10pt;" class="mr-4">Sign up</a>
    {% endif %}
  </div>
</nav>

<main role="main" class="container">
  <div class="row mt-2">
    <div class="col-md-12">
      {% if messages %}
      {% for message in messages %}
      <div class=" alert alert-success">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% block content %}{% endblock %}
    </div>
  </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

aspatal_app/templates/aspatal_app/prescription_list.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|All_Presciption
{% endblock %}
{% block content %}
<div class="container">
    {% if user.is_patient %}
    <h2>Your Medical History</h2>
    <br>
    <ul class="list-group">
        {% for obj in object_list %}
        <li class="list-group-item">
            <h3><strong>{{ obj.date }}</strong></h3>
            <p>Symptoms - {{ obj.symptoms }}</p>
            <p>Prescription - {{ obj.prescription }}</p>
            <button class="btn btn-primary">Learn More</button>
        </li>
        {% endfor %}
    {% endif %}
    {% if user.is_doctor %}
    <h2>Your Prescriptions</h2>
    <a href="{% url 'aspatal_app:doc-prescriptions-create' %}"><button class="btn btn-primary pull-right">Create New Prescription</button></a>
    <br> <br>
    <ul class="list-group">
        {% for obj in object_list %}
        <li class="list-group-item">
            <h3><strong>{{ obj.date }}</strong></h3>
            <p>Symptoms - {{ obj.symptoms }}</p>
            <p>Prescription - {{ obj.prescription }}</p>
            <p>Patient Name - {{ obj.patient }}</p>
        </li>
        {% endfor %}
    {% endif %}
    </ul>
</div>
{% endblock %}

aspatal_app/templates/aspatal_app/recp_dashboard.html
{% extends 'aspatal_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Life|Receptionist_Dashboard
{% endblock %}
{% block content %}
<div class="container">
    <h1 align="center">Dashboard</h1>
    <br>
    <ul class="list-group">
        <li class="list-group-item">
            <strong>Total Appointments</strong> - {{ totalApp }}
        </li>
        <li class="list-group-item">
            <strong>Appointments Done</strong> - {{ compApp }}
        </li>
        <li class="list-group-item">
            <strong>Upcoming Appointments</strong> - {{ pendApp }}
        </li>
    </ul>
</div>
<div class="row">
    <div class="col-md-5">
        <h3>Appointments -</h3>
        <div class="card card-body">
            <a href="{% url 'aspatal_app:appointment-create' %}"><button class="btn btn-primary">Create Appointment</button></a>
            <table class="table table-striped">
                <thead>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Doctor</th>
                    <th>Patient</th>
                    <th>Status</th>
                </thead>
                {% for obj in app_list %}
                <tr>
                    <td>{{ obj.date }}</td>
                    <td>{{ obj.time }}</td>
                    <td>{{ obj.doctor }}</td>
                    <td>{{ obj.patient }}</td>
                    <td>{{ obj.status }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <br>
    <div class="col-md-7">
        <h3>Last 5 Patients -</h3>
        <div class="card card-body">
            <a href="{% url 'users:profile-create' %}"><button class="btn btn-primary">Create Patient</button></a>
            <table class="table table-striped">
                <thead>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>Age</th>
                    <th>Update</th>
                    <th>Remove</th>
                </thead>
                {% for obj in pat_list %}
                <tr>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.phone }}</td>
                    <td>{{ obj.email }}</td>
                    <td>{{ obj.gender }}</td>
                    <td>{{ obj.age }}</td>
                    <td><a href="{% url 'users:profile-pk' pk=obj.user.id %}"><button class="btn btn-warning">Update</button></a></td>
                    <td><a href="{% url 'users:profile-delete' pk=obj.user.id %}"><button class="btn btn-danger">Delete</button></a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}